name: CI

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '**.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - '**.md'
    branches:
      - master

concurrency:
  group: '${{ github.repository }}-ci-${{ github.ref }}'
  cancel-in-progress: false

jobs:
  main:
    name: Test
    runs-on: rex-runner-s
    container: 526839183759.dkr.ecr.us-east-1.amazonaws.com/rex-gha-base
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Test
        run: |
          echo 'Hello World!'
